spring.application.name=data-cleaner

data.seao.db=jdbc:postgresql://localhost:5432/seao
data.seao.user=tlemy
data.seao.pass=pass1234

data.sql.supplier.select.all=select id, initcap(lower(s.seao_name::text)) AS supplier_name from supplier s order by supplier_name asc;
data.sql.supplier.select.similar=select id, initcap(lower(s.seao_name::text)) AS supplier_name from supplier s where word_similarity(?, s.seao_name::text) > 0.99 order by supplier_name asc;
data.sql.supplier.update.seao.name=update supplier s set seao_name  = ? where s.id  = ?;